# Generated by Django 5.1.2 on 2024-10-21 11:57

import app.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionarios',
            options={},
        ),
        migrations.AlterModelOptions(
            name='plansalario',
            options={},
        ),
        migrations.RemoveField(
            model_name='plansalario',
            name='nome',
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='cargo',
            field=models.CharField(max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='conta_inter',
            field=models.CharField(max_length=20, verbose_name='Conta Inter'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'O CPF deve ter 11 dígitos numéricos.')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='data_admissao',
            field=models.CharField(max_length=100, validators=[app.models.Funcionarios.validate_date_format], verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='data_nascimento',
            field=models.CharField(max_length=100, validators=[app.models.Funcionarios.validate_date_format], verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='funcao',
            field=models.CharField(max_length=100, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='proximo_exame',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[app.models.Funcionarios.validate_date_format], verbose_name='Próximo Exame'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='registro',
            field=models.CharField(max_length=50, verbose_name='Registro'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='ultimo_exame',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[app.models.Funcionarios.validate_date_format], verbose_name='Último Exame'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='arred',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Arredondamento'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='coparticipacao',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coparticipação'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='decimo_terceiro_ferias',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='13º de Férias'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='dias_trabalhados',
            field=models.IntegerField(verbose_name='Dias Trabalhados'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='ferias',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Férias'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcionarios', verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='geral',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Geral'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='ir_ferias',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IR Férias'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='mes',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='mes'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='mesAno',
            field=models.CharField(max_length=15, verbose_name='Mês e Ano'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='outras_entradas',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Outras Entradas'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='periculosidade',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Periculosidade'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='plano_saude',
            field=models.CharField(max_length=150, verbose_name='Plano de Saúde'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='qtde_dias_Mes',
            field=models.IntegerField(verbose_name='Qtde dias do mês'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='salario_familia',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Família'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='tipo_plano_saude',
            field=models.CharField(max_length=150, verbose_name='Tipo de plano de Saúde'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='troco',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Troco'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='vales_e_faltas',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Vales e Faltas'),
        ),
        migrations.AlterField(
            model_name='plansalario',
            name='vt',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Vale Transporte'),
        ),
    ]
