# Generated by Django 5.1.1 on 2024-10-16 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionarios',
            options={},
        ),
        migrations.AlterModelOptions(
            name='login',
            options={},
        ),
        migrations.AlterModelOptions(
            name='plansalario',
            options={},
        ),
        migrations.RemoveField(
            model_name='plansalario',
            name='nome',
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='cpf',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'O CPF deve ter 11 dígitos numéricos.')]),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='email',
            field=models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
