# Generated by Django 5.1.2 on 2024-10-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_funcionarios_options_alter_login_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='cargo',
            field=models.CharField(max_length=50, verbose_name='Status'),
        ),
    ]
